name: project
channels:
dependencies:

  - pip:
    - apscheduler=3.6.3
    - backports.zoneinfo=0.2.1
    - cachetools=4.2.2
    - certifi=2021.10.8
    - charset-normalizer=2.0.9
    - click=8.0.3
    - colorama=0.4.4
    - flask-cors=3.0.10
    - flask-httpauth=4.5.0
    - flask-sqlalchemy=2.5.1
    - flask=2.0.2
    - greenlet=1.1.2
    - idna=3.3
    - itsdangerous=2.0.1
    - jinja2=3.0.3
    - markupsafe=2.0.1
    - pip=21.3.1
    - psycopg2=2.9.2
    - python-telegram-bot=13.9
    - pytz-deprecation-shim=0.1.0.post0
    - pytz=2021.3
    - requests=2.26.0
    - setuptools=41.2.0
    - six=1.16.0
    - sqlalchemy=1.4.29
    - tornado=6.1
    - tzdata=2021.5
    - tzlocal=4.1
    - urllib3=1.26.7
    - werkzeug=2.0.2
